#!/usr/bin/env python

import citadel.nodes.root


class Header(citadel.nodes.root.Node):

    def __init__(self, yml, path):
        super(Header, self).__init__(yml, path)

    def to_bash(self):
        return [
            '#!/usr/bin/env bash',
            '\n### Generated by CITADel ###\n',
            'set -ue',
            'set -o pipefail\n',
        ]
