#!/usr/bin/env python

import logging
import os

import citadel.nodes.node


class Root(citadel.nodes.node.Base):

    def __init__(self, yml, path=[], environment=None):
        super(Root, self).__init__(yml, path)

        self.output.append('#!/usr/bin/env bash')
        self.output.append('')
        self.output.append('### Generated by CITADel ###')
        self.output.append('set -ue')
        self.output.append('set -o pipefail')
        self.output.append('')
        self.output.append('export PWD="%s"' % (os.getcwd()))
        self.output.append('')
        if environment:
            self.output.append('### CLI ENVIRONMENT args')
            for line in environment.split():
                if '=' in line:
                    name, value = line.split('=', 1)
                    # Periods make it an invalid identifier in bash
                    # so we ignore them
                    if '.' in name:
                        continue
                    self.output.append('export %s="%s"' % (name, value))
                else:
                    logging.debug('Ignoring invalid export line: %s', line)
